server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data_manage?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#????mapper.xml?????
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


